- name: Install google chrome
  ansible.builtin.apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- name: Fix potential missing dependencies
  ansible.builtin.apt:
    name: google-chrome-stable
    state: fixed
