- name: Check if pyenv is installed
  become: false
  ansible.builtin.stat:
    path: ~/.pyenv/bin/pyenv
  register: pyenv
- name: Download pyenv installer
  become: false
  when: pyenv.stat.exists == False
  ansible.builtin.get_url:
    url: https://pyenv.run
    dest: /tmp/pyenv.run
- name: Install pyenv
  become: false
  when: pyenv.stat.exists == False
  ansible.builtin.shell: bash /tmp/pyenv.run
- name: Setup shell environment for pyenv [.bashrc, .profile]
  become: false
  blockinfile:
    path: "~/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED pyenv setup DON'T MODIFY OR DELETE"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      command -v pyenv >/dev/null || export PATH="${PYENV_ROOT}/bin:$PATH"
      eval "$(pyenv init -)"
    state: present
    create: true
- name: Install dependencies for pyenv to be able to install python versions
  become: true
  ansible.builtin.package:
    name:
      - libssl-dev
      - liblzma-dev
      - libsqlite3-dev
      - libffi-dev
      - libbz2-dev
      - tk-dev
