- name: Setup Radar Demo
  hosts: dev
  vars:
    kernel_base: "6.2.0"
    kernel_patch: "39"
    kernel: "{{ kernel_base }}-{{ kernel_patch }}"
    repo_dir: "{{ playbook_dir | dirname }}"
  roles:
    - role: distupgrade
    - role: bash
    - role: launcher
    - role: kernel
    - role: libqdma
    - role: udev
    - role: socat
    - role: direnv
    - role: python
    - role: grub
  tasks:
    - name: Install System Packages
      become: true
      ansible.builtin.package:
        name:
          - chromium-browser
          - curl
          - htop
          - git
        state: present
