- name: Clone libqdma git repository
  become: false
  ansible.builtin.git:
    repo: 'https://github.com/Xilinx/dma_ip_drivers.git'
    dest: /tmp/dma_ip_drivers
    version: d66f224
    force: true
  register: libqdma
- name: Apply patch for newest kernel
  become: false
  ansible.builtin.command:
    cmd: git apply {{ playbook_dir}}/roles/libqdma/files/0001-QDMA-Add-support-for-6.4.x-kernel-version.patch
    chdir: /tmp/dma_ip_drivers
- name: Install build dependencies
  become: true
  ansible.builtin.package:
    name:
      - make
      - gcc-12
      - build-essential
      - libaio1
      - libaio-dev
- name: "Compile libqdma for Kernel {{ kernel }}"
  become: false
  ansible.builtin.shell:
    cmd: make KDIR=/lib/modules/{{ kernel }}-generic/build
    chdir: /tmp/dma_ip_drivers/QDMA/linux-kernel/
  when: libqdma.changed
- name: "Install qdma modules for Kernel {{ kernel }}"
  become: true
  ansible.builtin.shell:
    cmd: make install KDIR=/lib/modules/{{ kernel }}-generic/build
    chdir: /tmp/dma_ip_drivers/QDMA/linux-kernel/
  when: libqdma.changed
