- name: Install python3-serial
  become: true
  ansible.builtin.package:
    name:
      - python3-serial
    state: present
- name: Run poetry install
  become: false
  ansible.builtin.shell: "/home/{{ ansible_user_id }}/.local/bin/poetry install"
  args:
    chdir: "{{ playbook_dir }}/roles/radardemo_py_infra/files"
- name: Run poetry build
  become: false
  ansible.builtin.shell: "/home/{{ ansible_user_id }}/.local/bin/poetry build"
  args:
    chdir: "{{ playbook_dir }}/roles/radardemo_py_infra/files"
- name: Run pip3 install
  become: true
  ansible.builtin.shell: pip3 install dist/*.whl
  args:
    chdir: "{{ playbook_dir }}/roles/radardemo_py_infra/files"
