- name: Place the start_demo script in $HOME
  become: false
  ansible.builtin.copy:
    content: |
      #!/bin/bash
      SCRIPT=$(readlink -f "$0")
      SCRIPTPATH=$(dirname "$SCRIPT")
      cd {{ playbook_dir }}/../backend || exit 1
      eval "$(direnv export bash)"
      killall python3
      direnv allow .
      poetry install
      cd /
      cd {{ playbook_dir }}/../backend || exit 1
      python3 run.py &
      server_pid=$!
      google-chrome --app=http://127.0.0.1:5000 --password-store=basic --start-fullscreen
      kill $server_pid
    dest: ~/start_demo.sh
    mode: '0755'
- name: Place the icon in $HOME/.local/share
  become: false
  ansible.builtin.copy:
    src: radar.png
    dest: ~/.local/share/radar.png
    mode: '0644'
- name: Create launcher script
  become: false
  ansible.builtin.copy:
    dest: ~/.local/share/applications/radar-demo.desktop
    content: |
      [Desktop Entry]
      Type=Application
      #Terminal=true
      Name=Radar Demo
      Icon=/home/{{ ansible_user_id }}/.local/share/radar.png
      Exec=/home/{{ ansible_user_id }}/start_demo.sh
    mode: '0644'
